apiVersion: v1
kind: Namespace
metadata:
  name: wisecow


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  namespace: wisecow
  labels:
    app: wisecow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: yallavagdevi/wisecow:latest
        ports:
        - containerPort: 4499


---

apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  namespace: wisecow
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4499
  selector:
    app: wisecow